### ISSUE TITLE
Heplify not sending data to Homer

### ISSUE THREAD

**Issue by psanders** [sipcapture/heplify#26]
I just ran Homer using homer-docker with docker-compose. All containers seems to be running correctly.

<img width="1271" alt="screen shot 2018-01-20 at 11 43 59" src="https://user-images.githubusercontent.com/539774/35185776-498830f8-fdd7-11e7-9eea-63a5a111ac93.png">

I also have another container that has Asterisk and `heplify`. I using `heplify` with the following command:

`./heplify -hs 192.168.1.2:9060 -e -d fragment,payload,rtcp`

The sniffer is capturing the SIP packets but `heplify` does not appear to be sending the data to Homer.

<img width="1234" alt="screen shot 2018-01-20 at 11 46 36" src="https://user-images.githubusercontent.com/539774/35185794-9c4e3cce-fdd7-11e7-84a2-018164de9a66.png">

What am I doing wrong?

**Comment by negbie** [comment]
Hi psanders, 
I get the "Packets overall received, dropped by OS, dropped by interface" directly from your network interface. Packets since last minute sent comes from a counter inside heplify. Packets since last minute... comes from heplify too. When you look at the heplify stats you see that you have received 4 UDP packets and heplify has sent 4 packets. 

So most likely its something with the other side. Could you please look into the kamailio logs and mby there are some errors.

**Comment by psanders** [comment]
I'm able to see the packages on the Kamalio side using tcpdump. However, I have no experience using Kamalio.  I can't find the log file for Kamalio. Can you point me in the right direction before I close this thread?

**Comment by negbie** [comment]
Sure, you can search in the kamailio config for the route 
event_route[sipcapture:request]

Place there
xlog("L_CRIT","HEP Payload: $hep(0x00f)\n");

and have a look into syslog. Mby you can search for something similar in the homer google group
https://groups.google.com/forum/#!forum/homer-discuss

**Comment by psanders** [comment]
After all, there was nothing wrong with homer or heplify, except that for some reason homer ui defaults to a wrong date range. Thanks for the help.
