### ISSUE TITLE
filtering traffic by IP addresses

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/heplify#67]
i (finally) have a packet capture setup grabbing all sip packets in my lab.  Originally setup heplify on the packet-capturer to send the packets to heplify-server, which works well, but heplify doesn't seem to have a way to select packets based on IP (so i can filter out traffic from devices I'm not interested in).  

was thinking to use TC to filter the traffic and send it to heplify, which will then send it to heplify-server.  Any advice on a less convoluted solution?

**Comment by negbie** [comment]
Hi,
mby the flag -di will help you. It will scan the whole byte slice against that string. Latest heplify version can take multiple comma seperated strings

-di 192.168.1.1,192.168.1.2
will drop e.g following message
....
Contact: <sip:192.168.1.1:5260;transport=udp>
....

Be aware that it will go through the whole message so if it finds this strings inside the auth header or somewhere else it will drop that message.

**Comment by negbie** [comment]
Or when you are a little bit more creative you can use the -pr flag which is simply a bpf filter which expects a portrange but can be extended with anything else like

-pr "5060-5090 and not src host 200.57.7.204"

**Comment by negbie** [comment]
Keep in mind that the suggestion above won't work for erspan traffic.

**Comment by JonConnor** [comment]
awesome, will try the -pr flag.  I would imagine that would be must faster than having heplify scan the entire sip msg.. ?

**Comment by negbie** [comment]
Yes that would be faster but its hard to compare because they operate on totally different layers.

./heplify -i any -di "200.57.7.204" -t af_packet
would add around 100 nano seconds processing time compared to

./heplify -i any -pr "5060-5090 and not src host 200.57.7.204" -t af_packet
in case you want to drop message with the above src ip. I think you wouldn't even notice that extra 100ns. Again, you cannot really compare those two flags.
