### ISSUE TITLE
RCTP not being captured and amplify port range 

### ISSUE THREAD

**Issue by KyleHyde6** [sipcapture/heplify#73]
Hello to Everyone, im an old user from captagent but wanted to try Heplify as capture agent. 

How can i change RTCP capture ports?

Heplify captures SIP but not RTCP and i declared mode SIPTRCP when i start the Heplify agent. 

Also i have distinct ports from 5060 5080 5090 when im using sip, how can i capture on 5060 to 5092 and 6060 to 6092 ?

**Comment by negbie** [comment]
Hi,
heplify will listen on all ports for RTCP and you don't have to set the filter mode to SIPTRCP because it's the default. You can simply use the -pr flag like -pr 5060-6092 and you are good to go. Keep inn mind that you will need SIP traffic for RTCP correlation because the needed information are extracted from SDP. To debug RTCP correlation you could use -d rtcp

**Comment by negbie** [comment]
@KyleHyde6 Do you still need help or can I close this issue?

**Comment by KyleHyde6** [comment]
Yes!!! It worked!! really thanks im sorry forgot to post my answer!

**Comment by negbie** [comment]
No problem. Will close it now.
