### ISSUE TITLE
Duplicate requests and replies, "dedup" parameter?

### ISSUE THREAD

**Issue by MaxMuehlbronner** [sipcapture/heplify#98]
I've used a homer instance and just started heplify server on one machine and the client on the other one.

Setting it up is pretty easy, but i've immediately faced a problem: All of the requests/replies were duplicated, e.g. two INVITES, followed by two 100 trying, followed by two 183 session progress replies.

When checking the database, the entries are indeed duplicates, so every requests or reply exists two times(mysql db). I've found the "dedup" parameter for heplify, which seems to filter out the duplicate entries.

 But i am wondering why this is happening, i tried some things but never managed to solve this. Also, could this be a performance downfall if the heplify-server has to "check"(dedup) the requests and replies? Or is it not really a problem?

Heplify 1.47

**Comment by negbie** [comment]
Hi @MaxMuehlbronner 
do you have multiple vlan interfaces or floating ip's? When you start heplify with -i any (default) it captures all interfaces. So it could be that you capture 2 same packets. One with and one without vlan tag. I have setups where this is the case quite often and because of this I made this dedup flag.
It has almost no performance impact (maybe 1%).

**Comment by MaxMuehlbronner** [comment]
Wow that was fast, thanks. You are right, when i set it to a single interface it works perfectly fine! Very cool, i will look more into heplify now.
